### PR TITLE
Launcher icon

### PR DESCRIPTION
**Pull request by ocr-junky**

### CODE REVIEW

**Comment by ocr-junky** [comment]
Sorry, still the wrong filename somehow...

**Comment by pleft** [comment]
No problem, thanks, I merged your commits and I will change the filename

**Comment by ocr-junky** [comment]
Thanks, apparently it isn’t the best thing to do several things simultaneously…

**Comment by pleft** [comment]
It looks great! I updated my GameShell and the icon looks way better than my previous one! thanks for your contribution!

**Pull request merged**
